# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://tritechteal.com"
baseurl: ""


# --- main page --- #

# Name for site
name: TriTechTeal

# Short description for site
description: We are awesome for build solutions!
header-bg: "../img/header-bg.jpg"
header-logo: "../img/logos/logo.png"

# Social Share
social-logo: "https://tritechteal.com/img/logos/og-logo.png"
fb-ogtype: 'fb:app_id'

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  services: "#services"
  #portfolio: "#portfolio"
  team: "#team"
  career: "#career"
  contact: "#contact"

lead-text:
  intro: Welcome To TriTechTeal!
  heading: Need business solutions?
  button-text: Get a Quote
  button-url: "#contact"
  backgroud: "#"


# --- Services list --- #

services:
  heading: Services
  sub-heading: Things we do the best.

services-list:
  Web Development & Design:
    icon: "fa-globe"
    description: We offer web development in Core PHP and it's frameworks e.g. Laravel, CodeIgnitor, and Wordpress. We can modify the existing website/business solutions. You are being interested then you are at right place,  get a <a href="#contact">Quote</a>.
  Mobile Application Development:
    icon: "fa-mobile-alt"
    description: We have a vital skill in mobile application designing and development. We build, test and deploy the application. Our team good in Analytical, Creativity and Problem Solving. We focus on UI/UX, High Performance and Compatibility with the device.
  Technical Support:
    icon: "fa-headset"
    description: We helps you in fixing bug, optimization in software, Continuous deployment for software releases, Cloud Computing (AWS and Heroku). We offering Architecting on AWS for your web and mobile application.


# Contact Us
contact:
  heading: "Contact Us"
  subheading: Office No. 23, 4th floor, St No. 03, Near Munch Hutt Hostel City, Islamabad.

# --- social links list --- #
facebook: "https://www.facebook.com/tritechteal/"
twitter: "https://twitter.com/tritechteal"
linkedin: "https://www.linkedin.com/company/tritechteal"
github: "https://github.com/orgs/tritecht/"


# --- Web Statistics Section --- #

# Fill Google Analytics ID to track site using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50


# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

