# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://username.github.io"
baseurl: ""


# --- main page --- #

# Name for site
name: Tri Tech Teal

# Short description for site
description: We are awesome for build solutions!
header-bg: "../img/header-bg.jpg"

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  services: "#services"
  portfolio: "#portfolio"
  team: "#team"
  contact: "#contact"

lead-text:
  intro: Welcome To TriTechTeal!
  heading: Need business solutions?
  button-text: Get a Quote
  button-url: "#contact"
  backgroud: "#"


# --- Services list --- #

services:
  heading: Services
  sub-heading: Things we do the best.

services-list:
  Web Development & Design:
    icon: "fa-globe"
    description: We offer web development in Core PHP and it's frameworks e.g. Laravel, CodeIgnitor, and Wordpress. We can modify the existing website/business solutions. You are being interested then you are at right place,  get a <a href="#contact">Quote</a>.
  Mobile Application Development:
    icon: "fa-mobile-alt"
    description: We have a vital skill in mobile application designing and development. We build, test and deploy the application. Our team good in Analytical, Creativity and Problem Solving. We focus on UI/UX, High Performance and Compatibility with the device.
  Technical Support:
    icon: "fa-headset"
    description: We helps you in fixing bug, optimization in software, Continuous deployment for software releases, Cloud Computing (AWS and Heroku). We offering Architecting on AWS for your web and mobile application.


# --- Portfolio list --- #
## Thumbnail image size is 400x300
## Full image size is 700x933

portfolio:
  heading: Portfolio
  sub-heading: Lorem ipsum dolor sit amet consectetur.

portfolio-list:
  first-project:
    title: This is first Project
    thumbnail-image-src: "img/portfolio/01-thumbnail.jpg"
    thumbnail-image-alt: "#"
    full-image-src: "img/portfolio/01-full.jpg"
    full-image-alt: "Full image alt"
    description: Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!
    date: January 2017
    client: Threads
    category: Illustration


# --- team list --- #
# image size is: 500x500

team:
  heading: OUR AMAZING TEAM
  sub-heading: Alone we can do so <b>little</b>; together we can do so <b>much<b> – Helen Keller

team-list:
  Asif Raza:
    name: Asif Raza
    designation: Project Manager / Founder
    image: "img/team/1.png"
    facebook: "https://www.facebook.com/raoasifraza1"
    linkedin: "https://www.linkedin.com/in/raoasifraza/"
    twitter: "https://twitter.com/raoasifraza1"
    github: "https://github.com/raoasifraza11"

  Rehman Masqood:
    name: Rehman Masqood
    designation: Mobile Application / Wordpress Developer
    image: "img/team/2.jpg"
    facebook: "#"
    linkedin: "#"
    twitter: "#"
    github: "#"

  Arslan Ahmad:
    name: Arslan Ahmad
    designation: Web / Laravel / PHP Developer
    image: "img/team/3.jpg"
    facebook: "#"
    linkedin: "#"
    twitter: "#"
    github: "#"


team-quote: None of us, including me, ever do great things. But we can all do small things, with great love, and together we can do something wonderful." – Mother Teresa


# Contact Us
contact:
  heading: "Contact Us"
  subheading: Office No. 23, 4th floor, St No. 03, Near Munch Hutt Hostel City, Islamabad.

# --- social links list --- #
facebook: "https://www.facebook.com/tritechteal/"
twitter: "https://twitter.com/tritechteal"
linkedin: "https://www.linkedin.com/company/tritechteal"
github: "https://github.com/orgs/tritecht/"


# --- Web Statistics Section --- #

# Fill Google Analytics ID to track site using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50


# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

